apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aceivt
spec:
  source:
    git:
      uri: https://github.com/peterajessup/ibm-ace-ivt-build
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'demoace:v0.92'
      alias: true
  strategy:
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key
      dockerfilePath: .
