apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: is2
  namespace: ace
spec:
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: '0.5'
            memory: 2Gi
          requests:
            cpu: '0.5'
            memory: 2Gi
  version: 12.0.5.0-r2
  imagePullSecrets:
    name: ibm-entitlement-key
  license:
    accept: true
    license: L-APEH-C9NCDM
    use: AppConnectEnterpriseNonProduction
  useCommonServices: true
  enableMetrics: true
  barURL: https://db-ace-dash-dash:3443/v1/directories/ivtnk?5eb3d49b-4803-457f-91b8-1d6e749e0ef1
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  adminServerSecure: false
  tracing:
    enabled: true
    namespace: od
  logFormat: basic
  configurations: ["mqpolicy", "key.jks", "httpsconf", "scramparms"]
