apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: is2
  namespace: ace
spec:
  pod:
    containers:
      runtime:
        image: image-registry.openshift-image-registry.svc:5000/ace/demoace:v0.94
  version: 11.0.0.11-r1
  imagePullSecrets:
    name: default-dockercfg-zn29f
  imagePullPolicy: Always
  license:
    accept: true
    license: L-APEH-BPUCJK
    use: AppConnectEnterpriseProduction
  useCommonServices: true
  replicas: 1
  service:
    endpointType: https
  designerFlowsOperationMode: disabled
  tracing:
    enabled: true
    namespace: od
  logFormat: basic
  configurations: ["mqpolicy", "key.jks", "kafkapolicy", "httpsconf", "scramparms", "es-cert-ace.p12"]
