apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: aceivt
spec:
  source:
    git:
      uri: https://github.com/peterajessup/ibm-ace-ivt-build
      ref: master
  output:
    to:
      kind: ImageStreamTag
      name: 'demoace:v0.96'
#      name: 'iagace:v12.0.5.0-r1'
  strategy:
    dockerStrategy:
      pullSecret:
        name: ibm-entitlement-key
      dockerfilePath: .
